title: 我与自己
author: puzz1ing
email: lethinkrong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
看吸血鬼日记的时候，哥哥有一个情绪开关。两年前写小传，发现自己也有压抑着的情感。舞舞舞，写写写这是自留地，只求对每个当下的自己诚实快写慢改company流动的

# social links

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
