title: 我与自己
author: puzz1ing
email: lethinkrong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
When watching vampire diaries, I found Stephen has an emotional switch. Two years ago, I wrote a biography and found that I also had repressed emotions. Dance, dance, write and write. This is a private area. I only want to be honest with each of my current self. Write fast and change slowly. Company. flows
# social links

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
